"""Generate web and Dart translation maps from the shared Spanish catalog."""
import json
from pathlib import Path

root = Path(__file__).resolve().parents[1]
translations = json.loads((root / 'localization/es.json').read_text())
(root / 'translations.js').write_text(
    '// Generated by scripts/generate-localization.py; edit localization/es.json.\n'
    'const splashSpanish = ' + json.dumps(translations, ensure_ascii=False, indent=2) + ';\n'
    "if (typeof module !== 'undefined') module.exports = splashSpanish;\n"
)
# JSON quoted strings are also Dart strings; escape interpolation markers.
(root / 'app/lib/core/localization/spanish.dart').write_text(
    '// Generated by scripts/generate-localization.py; edit localization/es.json.\n'
    'const spanish = <String, String>' + json.dumps(translations, ensure_ascii=False, indent=2).replace('$', r'\$') + ';\n'
)
